Algoritmo "exercicio_14"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joao Gabriel C
// Data atual  : 19/03/2024
Var
   // Seção de Declarações das variáveis
   x : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o numero: ")
   leia(x)

   se x > 10 entao
      escreval("O numero eh maior que 10")
   senao
      escreval("O numero eh menor que 10")
   fimse

Fimalgoritmo