Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joao Gabriel
// Data atual  : 14/03/2024
Var
// Seção de Declarações das variáveis 
x, y : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Escreva o valor de x:")
leia(x)
y <- x - 1
escreval("O antecessor deste numero eh:", y)

Fimalgoritmo