Algoritmo "exercicio19"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joao Gabriel c
// Data atual  : 04/04/2024
Var
// Seção de Declarações das variáveis
numero1, numero2:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o primeiro valor:", numero1)
leia(numero1)
escreval("Digite o segundo valor:", numero2)
leia(numero2)

se numero1 = numero2 entao
escreval("os valores são iguais")
fimse

se numero1 > numero2 entao
escreval("o valor 1 é maior que o 2")
fimse

se numero1 < numero2 entao
escreval("o valor 2 é maior que o 1")
fimse


Fimalgoritmo