Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Conversor de Temperatura
// Autor(a)    : João Gabriel C Mallmann
// Data atual  : 18/03/2024
Var
// Seção de Declarações das variáveis 
GrauF, GrauC : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor de graus em Fahrenheit:")
leia(GrauF)
GrauC <- (GrauF - 32) * 5/9
Escreva("O valor desta temperatura em Graus Celsius será:", GrauC, "°")



Fimalgoritmo