Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joao Gabriel Cavalcante Mallmann
// Data atual  : 14/03/2024
Var
// Seção de Declarações das variáveis 
area, base,  altura : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva a base do retangulo")
leia(base)
escreval("Escreva a area do retangulo")
leia(altura)
area <- base * altura
escreval("A area do retangulo eh de:", area)

Fimalgoritmo