Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : o programa deve apresentar o resultado do produto (variável P) do primeiro com o terceiro valor, e o resultado do produto (variável P) do primeiro com o terceiro valor, e o resultado da soma (variável S) do segundo com o quarto valor.
// Autor(a)    : João Gabriel
// Data atual  : 12/04/2024
Var
// Seção de Declarações das variáveis 
A, B, C, D, P, S: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor de A:")
leia(A)
escreval("Digite o valor de B:")
leia(B)
escreval("Digite o valor de C:")
leia(C)
escreval("Digite o valor de D:")
leia(D)

P <- A * C
S <- B + D
escreval("O produto do primeiro com o terceiro é ", P)
escreval("A soma do segundo com o quarto valor é ", S)

Fimalgoritmo