Algoritmo "5.1.1H"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   :Elaborar um programa que apresente os valores de conversão de graus Celsius em Fahrenheit, de 10 em 10 graus
// Autor(a)    : João Gabriel
// Data atual  : 22/04/2024
Var
// Seção de Declarações das variáveis 
celsius: inteiro
fahren: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


para celsius de 10 ate 100 passo 10 faca
escreval(celsius ," Graus Celsius igual a")
fahren <- (9*celsius + 160)/5
escreval(fahren ," Graus Fahrenheit")
escreval("")
fimpara



Fimalgoritmo