Algoritmo "5.1.1A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer
// Autor(a)    : João Gabriel
// Data atual  : 22/04/2024
Var
// Seção de Declarações das variáveis 
valor, contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um valor")
leia(valor)
enquanto contadora <= 10 faca
escreval(valor , " x ", contadora, " = ", valor * contadora)
contadora<- contadora +1
fimenquanto

Fimalgoritmo