Algoritmo "5.1.1B"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100)
// Autor(a)    : João Gabriel
// Data atual  : 22/04/2024
Var
   // Seção de Declarações das variáveis
   contadora, valor: inteiro

Inicio
   // Seção de Comandos
   valor <- 0
   enquanto contadora < 100 faca
   valor <- valor + contadora
   escreval(valor)
   contadora <- contadora + 1
   fimenquanto

Fimalgoritmo