Algoritmo "Manzano4k"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Elaborar um programa que efetue a leitura de um determinado valor inteiro, e efetue a sua apresentação, caso o valor não seja maior que três
// Autor(a)    : João G
// Data atual  : 18/04/2024
Var
// Seção de Declarações das variáveis
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite um número")
leia(valor)

se valor <= 3 entao
escreval("O valor é de ", valor)
senao
escreval("Valor não permitido")
fimse

Fimalgoritmo