Algoritmo "Manzano7a"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Leitura e Conversão Celsius para Fahrenheit
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2024
Var
// Seção de Declarações das variáveis 
celsius: inteiro
fahren: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite a temperatura em Celsius:")
leia(celsius)
fahren <- (9 * celsius + 160) / 5
escreval("A conversão desta temperatura para fahrenheit é de:", fahren)

Fimalgoritmo